# Generated by Django 6.0.4 on 2026-05-01 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name='Номер места')),
                ('shelf_type', models.CharField(choices=[('TOP', 'Верхняя'), ('BOTTOM', 'Нижняя'), ('SIDE_TOP', 'Боковая верхняя'), ('SIDE_BOTTOM', 'Боковая нижняя')], max_length=20, verbose_name='Тип полки')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Схема мест',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='TrainComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagon_number', models.IntegerField(verbose_name='Номер вагона')),
                ('class_name', models.CharField(max_length=50, verbose_name='Класс')),
                ('cost_coef', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэф. стоимости')),
            ],
            options={
                'verbose_name': 'Вагон',
                'verbose_name_plural': 'Вагоны',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('details', models.TextField(blank=True, verbose_name='Доп. информация')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журнал действий',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Забронирован'), ('CONFIRMED', 'Подтвержден'), ('COMPLETED', 'Выполнен'), ('CANCELLED', 'Отменен')], default='BOOKED', max_length=20, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена доп. услуг')),
                ('auto_upgrade', models.BooleanField(default=False, verbose_name='Авто-повышение класса')),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_end', to='booking.station', verbose_name='Станция прибытия')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.seatlayout', verbose_name='Место')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_start', to='booking.station', verbose_name='Станция посадки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wagon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.traincomp', verbose_name='Вагон')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='BookedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('extra_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.extraservice', verbose_name='Услуга')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Заказанная услуга',
                'verbose_name_plural': 'Заказанные услуги',
            },
        ),
        migrations.AddField(
            model_name='seatlayout',
            name='wagon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.traincomp', verbose_name='Вагон'),
        ),
        migrations.AddField(
            model_name='traincomp',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip', verbose_name='Рейс'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=10, verbose_name='Платформа')),
                ('duration', models.IntegerField(default=0, help_text='Стоянка в минутах', verbose_name='Стоянка (мин)')),
                ('time_from_start', models.IntegerField(help_text='Время от начала пути в минутах', verbose_name='Время от старта (мин)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость отрезка')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.station', verbose_name='Станция')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Остановка маршрута',
                'verbose_name_plural': 'Остановки маршрутов',
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_details', models.CharField(blank=True, max_length=255, verbose_name='Детали маршрута')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки на уведомления',
            },
        ),
        migrations.CreateModel(
            name='UserDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PASSPORT', 'Паспорт РФ'), ('BIRTH_CERT', 'Свидетельство о рождении')], max_length=20, verbose_name='Тип документа')),
                ('doc_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы пользователей',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.userdoc', verbose_name='Документ'),
        ),
    ]
