# Generated by Django 6.0.4 on 2026-05-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatlayout',
            name='allows_animals',
            field=models.BooleanField(default=False, verbose_name='С животными'),
        ),
        migrations.AddField(
            model_name='seatlayout',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('M', 'Мужское'), ('F', 'Женское')], max_length=10, null=True, verbose_name='Пол купе'),
        ),
    ]
